#!/usr/bin/env python
# encoding: utf-8

name = "Seed"
shortDesc = u""
longDesc = u"""

"""
autoGenerated=True
entry(
    index = 0,
    label = "X + CH3OH <=> CH3OHX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 1,
    label = "X + X + O2 <=> OX + OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.0436,
        n = -0.206,
        Ea = (1500, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 2,
    label = "X + X + H2 <=> HX + HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.032,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 3,
    label = "X + H <=> HX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 4,
    label = "X + X + CH3OH <=> HX + OC[Ni]",
    degeneracy = 3.0,
    kinetics = StickingCoefficient(
        A = 0.03,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 5,
    label = "X + X + OCCO <=> OC[Ni] + OC[Ni]",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(
        A = 0.02,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 6,
    label = "HX + HOX <=> X + X + H2O",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.85e+16, 'm^2/(mol*s)'),
        n = 0.086,
        Ea = (41500, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 7,
    label = "HOX + HOX <=> X + H2O + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.34e+16, 'm^2/(mol*s)'),
        n = 0.274,
        Ea = (92300, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 8,
    label = "X + OH <=> HOX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 9,
    label = "X + HOX <=> HX + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.25e+16, 'm^2/(mol*s)'),
        n = 0.188,
        Ea = (29600, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 32 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 32 HOX_1 + Ni_4 <=> OX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 10,
    label = "X + OC[Ni] <=> HX + OC=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (174.395, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 11,
    label = "HOX + OC=[Ni] <=> OX + OC[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 12,
    label = "X + OC=[Ni] <=> HX + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (119.584, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 13,
    label = "OX + OC=[Ni] <=> HOX + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 14,
    label = "OC=[Ni] + OC=[Ni] <=> OC[Ni] + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 15,
    label = "X + H2 <=> H2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 16,
    label = "X + H2O <=> H2OX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 17,
    label = "X + HO2X <=> OX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (142.881, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 18,
    label = "X + OC(O)=[Ni] <=> HOX + OC#[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (123.978, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 19,
    label = "OX + OC(O)=[Ni] <=> OC#[Ni] + HO2X",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 20,
    label = "X + OC(O)[Ni] <=> HOX + OC=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (377.41, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Dissociation
""",
)

entry(
    index = 21,
    label = "HO2X + OC=[Ni] <=> OX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 22,
    label = "X + OC(O)[Ni] <=> HX + OC(O)=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (373.015, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 23,
    label = "OC[Ni] + OC(O)=[Ni] <=> OC=[Ni] + OC(O)[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 24,
    label = "HOX + OC(O)=[Ni] <=> OX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 25,
    label = "OC=[Ni] + OC(O)=[Ni] <=> OC#[Ni] + OC(O)[Ni]",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 26,
    label = "OC=[Ni] + OC(O)=[Ni] <=> OC#[Ni] + OC(O)[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 27,
    label = "OC=[Ni] + OC(O)=[Ni] <=> OC#[Ni] + OC(O)[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 28,
    label = "OC#[Ni] + OC(O)[Ni] <=> OC=[Ni] + OC(O)=[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (301.704, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 29,
    label = "X + OC#[Ni] <=> HOX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (252.358, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 30,
    label = "CX + HO2X <=> OX + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 31,
    label = "OC#[Ni] + OC=[Ni] <=> CX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 32,
    label = "CX + OC(O)=[Ni] <=> OC#[Ni] + OC#[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 33,
    label = "X + CO <=> OCX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.5,
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 34,
    label = "X + OCX <=> OX + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.75e+09, 'm^2/(mol*s)'),
        n = 0,
        Ea = (116200, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 35,
    label = "HOX + CX <=> HX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.88e+21, 'm^2/(mol*s)'),
        n = 0.188,
        Ea = (62500, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 36,
    label = "OCX + OCX <=> X + CO2 + CX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.62e+10, 'm^2/(mol*s)'),
        n = 0.5,
        Ea = (241700, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 37,
    label = "OCX + OX <=> X + X + CO2",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (123600, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 38,
    label = "X + CO <=> COX",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 39,
    label = "X + X + CH3OH <=> HX + CO[Ni]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.01,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 40,
    label = "X + CH3OOX <=> OX + CO[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (144.651, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 41,
    label = "HX + CH3X <=> CH4 + X + X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.44e+18, 'm^2/(mol*s)'),
        n = -0.087,
        Ea = (63400, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 42,
    label = "HOX + CH3X <=> CH4 + X + OX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.98e+18, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (25800, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 43,
    label = "X + X + C2H6 <=> CH3X + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.01,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 44,
    label = "X + CH3 <=> CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 45,
    label = "X + X + CH3OH <=> HOX + CH3X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.01,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 46,
    label = "X + CO[Ni] <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (169.59, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 47,
    label = "X + OC[Ni] <=> HOX + C=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (164.568, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 48,
    label = "C=[Ni] + HO2X <=> OX + OC[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 49,
    label = "OC[Ni] + OC=[Ni] <=> C=[Ni] + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 50,
    label = "C=[Ni] + OC(O)=[Ni] <=> OC[Ni] + OC#[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 51,
    label = "CX + OC[Ni] <=> OC#[Ni] + C=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 52,
    label = "HX + C=[Ni] <=> X + CH3X",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (3.09e+19, 'm^2/(mol*s)'),
        n = -0.087,
        Ea = (57200, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 16 CH2X_3 + HX_5 <=> CH3X_1 + Ni_4 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 16 CH2X_3 + HX_5 <=> CH3X_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 53,
    label = "HOX + C=[Ni] <=> OX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.39e+17, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (19000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 24 CH2X_1 + HOX_3 <=> CH3X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 54,
    label = "OC[Ni] + C=[Ni] <=> CH3X + OC=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 55,
    label = "C=[Ni] + OC=[Ni] <=> CH3X + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 56,
    label = "CH3X + OC(O)=[Ni] <=> C=[Ni] + OC(O)[Ni]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (1.5e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 57,
    label = "X + OC=[Ni] <=> HOX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (141.43, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 58,
    label = "OX + OC=[Ni] <=> CHX + HO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 59,
    label = "OC=[Ni] + OC=[Ni] <=> CHX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 60,
    label = "CHX + OC(O)=[Ni] <=> OC#[Ni] + OC=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 61,
    label = "HX + CX <=> X + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.7e+20, 'm^2/(mol*s)'),
        n = -0.5,
        Ea = (157900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 20 CX_3 + HX_5 <=> CHX_1 + Ni_4 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 20 CX_3 + HX_5 <=> CHX_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 62,
    label = "CX + OC[Ni] <=> CHX + OC=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 63,
    label = "HOX + CX <=> OX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.43e+17, 'm^2/(mol*s)'),
        n = -0.312,
        Ea = (118900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 28 HOX_3 + CX_1 <=> OX_5 + CHX_4  in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 64,
    label = "CHX + OC#[Ni] <=> CX + OC=[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (132.057, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 65,
    label = "CX + OC=[Ni] <=> CHX + OC#[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 66,
    label = "CHX + OC(O)=[Ni] <=> CX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 67,
    label = "CX + CH3X <=> CHX + C=[Ni]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (1.5e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 68,
    label = "HX + CHX <=> X + C=[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (9.77e+20, 'm^2/(mol*s)'),
        n = -0.087,
        Ea = (81000, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 18 CHX_3 + HX_5 <=> CH2X_1 + Ni_4 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 18 CHX_3 + HX_5 <=> CH2X_1 + Ni_4 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 69,
    label = "HOX + CHX <=> OX + C=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (4.4e+18, 'm^2/(mol*s)'),
        n = 0.101,
        Ea = (42400, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training\nThis reaction matched rate rule [Abstracting;R-H]\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Matched reaction 26 CHX_1 + HOX_3 <=> CH2X_4 + OX_5 in Surface_Abstraction/training
This reaction matched rate rule [Abstracting;R-H]
family: Surface_Abstraction
""",
)

entry(
    index = 70,
    label = "C=[Ni] + OC=[Ni] <=> CHX + OC[Ni]",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 71,
    label = "C=[Ni] + OC=[Ni] <=> CHX + OC[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 72,
    label = "CHX + OC=[Ni] <=> OC#[Ni] + C=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 73,
    label = "C=[Ni] + OC(O)=[Ni] <=> CHX + OC(O)[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 74,
    label = "CX + C=[Ni] <=> CHX + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 75,
    label = "C=[Ni] + C=[Ni] <=> CH3X + CHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 76,
    label = "C=[Ni] + OC=[Ni] <=> CHX + OC[Ni]",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 77,
    label = "CHX + OC[Ni] <=> C=[Ni] + OC=[Ni]",
    degeneracy = 2.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 78,
    label = "CHX + OC#[Ni] <=> CX + OC=[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (132.057, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 79,
    label = "CX + OC=[Ni] <=> CHX + OC#[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 80,
    label = "OX + CHX <=> X + CXHO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (4.59e+16, 'm^2/(mol*s)'),
        n = 0,
        Ea = (109900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 81,
    label = "X + X + CH2O <=> HX + CXHO",
    degeneracy = 2.0,
    kinetics = StickingCoefficient(
        A = 0.02,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 82,
    label = "X + HCO <=> CXHO",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 83,
    label = "X + X + CH3CHO <=> CH3X + CXHO",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.01,
        n = 0,
        Ea = (41.84, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Dissociative',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite1;VacantSite2]
Euclidian distance = 0
family: Surface_Adsorption_Dissociative
""",
)

entry(
    index = 84,
    label = "X + CXHO <=> HX + OCX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.71e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 48 CXHO_1 + Ni_4 <=> OCX_3 + HX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 85,
    label = "CXHO + OC=[Ni] <=> OCX + OC[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 86,
    label = "OX + CXHO <=> OCX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 87,
    label = "CXHO + OC#[Ni] <=> OCX + OC=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 88,
    label = "CXHO + OC(O)=[Ni] <=> OCX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 89,
    label = "CXHO + C=[Ni] <=> OCX + CH3X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 90,
    label = "CHX + CXHO <=> OCX + C=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 91,
    label = "CX + CXHO <=> OCX + CHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 92,
    label = "X + OC(O)O[Ni] <=> OX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (126.572, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 93,
    label = "CH4 + X <=> CH4X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 94,
    label = "X + CO2 <=> CO2X",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 95,
    label = "X + COC(O)=[Ni] <=> CO[Ni] + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (107.527, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 96,
    label = "OX + COC(O)=[Ni] <=> CH3OOX + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 97,
    label = "X + CH3OCHOHX <=> CO[Ni] + OC=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (360.537, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 98,
    label = "CH3OOX + OC=[Ni] <=> OX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 99,
    label = "X + CH3OCHOHX <=> HX + COC(O)=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (372.594, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 100,
    label = "OC[Ni] + COC(O)=[Ni] <=> OC=[Ni] + CH3OCHOHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 101,
    label = "HOX + COC(O)=[Ni] <=> OX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 102,
    label = "OC=[Ni] + COC(O)=[Ni] <=> OC#[Ni] + CH3OCHOHX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 103,
    label = "OC=[Ni] + COC(O)=[Ni] <=> OC#[Ni] + CH3OCHOHX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 104,
    label = "OC(O)=[Ni] + CH3OCHOHX <=> OC(O)[Ni] + COC(O)=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 105,
    label = "CH3X + COC(O)=[Ni] <=> C=[Ni] + CH3OCHOHX",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (1.5e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 106,
    label = "C=[Ni] + COC(O)=[Ni] <=> CHX + CH3OCHOHX",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (1e+18, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 107,
    label = "CHX + COC(O)=[Ni] <=> CX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 108,
    label = "CXHO + COC(O)=[Ni] <=> OCX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 109,
    label = "OC=[Ni] + COC(O)=[Ni] <=> OC#[Ni] + CH3OCHOHX",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (40, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 110,
    label = "OC#[Ni] + CH3OCHOHX <=> OC=[Ni] + COC(O)=[Ni]",
    degeneracy = 1.0,
    duplicate = True,
    kinetics = SurfaceArrhenius(
        A = (5e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (301.202, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Abstracting;R-H]\nEuclidian distance = 0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Abstracting;R-H]
Euclidian distance = 0
family: Surface_Abstraction
""",
)

entry(
    index = 111,
    label = "X + COC(O)O[Ni] <=> OX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (126.994, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 112,
    label = "X + OC(O)OO[Ni] <=> OX + OC(O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0.93959, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 113,
    label = "X + OCCO <=> OCCO.[Ni]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_vdW',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_vdW
""",
)

entry(
    index = 114,
    label = "X + HOCXO <=> X + CO2 + HX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (3.73e+16, 'm^2/(mol*s)'),
        n = 0.475,
        Ea = (33600, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 115,
    label = "HOX + CXHO <=> HX + HOCXO",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (2.28e+16, 'm^2/(mol*s)'),
        n = 0.263,
        Ea = (15900, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
    ),
    longDesc = 
u"""
Originally from reaction library: Deutschmann_Ni
""",
)

entry(
    index = 116,
    label = "HOCXO + C=[Ni] <=> OCX + OC[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 117,
    label = "X + HOCXO <=> OCX + HOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1.46e+20, 'm^2/(mol*s)'),
        n = -0.213,
        Ea = (54300, 'J/mol'),
        T0 = (1, 'K'),
        Tmin = (298, 'K'),
        Tmax = (2000, 'K'),
        comment = 'Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training\nThis reaction matched rate rule [Combined;VacantSite]\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Matched reaction 44 HOCXO_1 + Ni_4 <=> OCX_3 + HOX_5 in Surface_Dissociation/training
This reaction matched rate rule [Combined;VacantSite]
family: Surface_Dissociation
""",
)

entry(
    index = 118,
    label = "HOCXO + CHX <=> OCX + OC=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 119,
    label = "CX + HOCXO <=> OCX + OC#[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 120,
    label = "OX + HOCXO <=> OCX + HO2X",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 121,
    label = "HOCXO + OC#[Ni] <=> OCX + OC(O)=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 122,
    label = "HOCXO + OC=[Ni] <=> OCX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 123,
    label = "X + COC(O)OO[Ni] <=> OX + COC(O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0.93959, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 124,
    label = "X + CH3O <=> CO[Ni]",
    degeneracy = 1.0,
    kinetics = StickingCoefficient(
        A = 0.1,
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Adsorbate;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Adsorption_Single',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Adsorbate;VacantSite]
Euclidian distance = 0
family: Surface_Adsorption_Single
""",
)

entry(
    index = 125,
    label = "X + CH3OCOX <=> OCX + CO[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (271.545, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 126,
    label = "OCX + CH3OOX <=> OX + CH3OCOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 127,
    label = "OCX + COC(O)=[Ni] <=> OC#[Ni] + CH3OCOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 128,
    label = "OC=[Ni] + CH3OCOX <=> OCX + CH3OCHOHX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-O]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 129,
    label = "X + COC(=O)O[Ni] <=> OX + CH3OCOX",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (160.917, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 130,
    label = "X + COC(=O)OO[Ni] <=> OX + COC(=O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (41.8266, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 131,
    label = "X + O=C([Ni])C(O)O <=> OCX + OC(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (116.565, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 132,
    label = "OX + O=C([Ni])C(O)O <=> OCX + OC(O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 133,
    label = "X + OC(O)C(O)(O)[Ni] <=> OC(O)[Ni] + OC(O)=[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (207.91, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 134,
    label = "OC(O)=[Ni] + OC(O)O[Ni] <=> OX + OC(O)C(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 135,
    label = "OC(O)=[Ni] + O=C([Ni])C(O)O <=> OCX + OC(O)C(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]\nEuclidian distance = 1.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-C]
Euclidian distance = 1.0
family: Surface_Abstraction
""",
)

entry(
    index = 136,
    label = "X + OC(O)C(O)(O)O[Ni] <=> OX + OC(O)C(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (132.728, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 137,
    label = "OC[Ni] + OC(O)=[Ni] <=> C=[Ni] + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 138,
    label = "X + OC(O)(O)[Ni] <=> HOX + OC(O)=[Ni]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (3e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (358.357, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
Multiplied by reaction path degeneracy 3.0
family: Surface_Dissociation
""",
)

entry(
    index = 139,
    label = "OC=[Ni] + OC(O)=[Ni] <=> CHX + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 140,
    label = "OC#[Ni] + OC(O)=[Ni] <=> CX + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 141,
    label = "HO2X + OC(O)=[Ni] <=> OX + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 142,
    label = "OC(O)=[Ni] + OC(O)=[Ni] <=> OC#[Ni] + OC(O)(O)[Ni]",
    degeneracy = 2.0,
    kinetics = SurfaceArrhenius(
        A = (2e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 143,
    label = "OC=[Ni] + OC(O)(O)[Ni] <=> OC(O)[Ni] + OC(O)=[Ni]",
    degeneracy = 3.0,
    kinetics = SurfaceArrhenius(
        A = (3e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nMultiplied by reaction path degeneracy 3.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
Multiplied by reaction path degeneracy 3.0
family: Surface_Abstraction
""",
)

entry(
    index = 144,
    label = "HOCXO + OC(O)=[Ni] <=> OCX + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+15, 'm^2/(mol*s)'),
        n = 0,
        Ea = (80, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]\nEuclidian distance = 2.0\nfamily: Surface_Abstraction',
    ),
    longDesc = 
u"""
Estimated using template [Abstracting;Donating] for rate rule [Abstracting;R-OH]
Euclidian distance = 2.0
family: Surface_Abstraction
""",
)

entry(
    index = 145,
    label = "X + OC(O)(O)O[Ni] <=> OX + OC(O)(O)[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (127.145, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 146,
    label = "X + OC(O)(O)OO[Ni] <=> OX + OC(O)(O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0.93959, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

entry(
    index = 147,
    label = "X + OC(O)C(O)(O)OO[Ni] <=> OX + OC(O)C(O)(O)O[Ni]",
    degeneracy = 1.0,
    kinetics = SurfaceArrhenius(
        A = (1e+17, 'm^2/(mol*s)'),
        n = 0,
        Ea = (0, 'kJ/mol'),
        T0 = (1, 'K'),
        Tmin = (200, 'K'),
        Tmax = (3000, 'K'),
        comment = 'Exact match found for rate rule [Combined;VacantSite]\nEuclidian distance = 0\nfamily: Surface_Dissociation',
    ),
    longDesc = 
u"""
Exact match found for rate rule [Combined;VacantSite]
Euclidian distance = 0
family: Surface_Dissociation
""",
)

